apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <PROJECT>-order-service
#  namespace: <PROJECT>
  labels:
    app: <PROJECT>-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <PROJECT>-order-service
  template:
    metadata:
      labels:
        app: <PROJECT>-order-service
    spec:
      containers:
        - image: <DOCKER_IMAGE>
          name: <PROJECT>-order-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http-server
      imagePullSecrets:
        - name: icp-ordproc-secret
