apiVersion: v1
kind: Service
metadata:
  name: ordproc-order-service
  labels:
    app: ordproc-order-service
spec:
  type: NodePort
  ports:
    - port: 8081
      name: http
  selector:
    app: ordproc-order-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordproc-order-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ordproc-order-service
        version: v1
    spec:
      containers:
        - name: ordproc-order-service
          image: gandigit/ordproc-order-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
